const initData = [
    {
        rating: {
            rate: 5,
            count: 0,
        },
        _id: '675c019144ad6011ea4eced1',
        title: 'Gấu Bông Minions Niềng Răng',
        image: 'https://gaubongonline.vn/wp-content/uploads/2022/07/minion-nieng-rang-3.jpg',
        description: 'Gấu Bông Minions Niềng Răng\r\n',
        price: 55500,
        amount: 0,
        seller: 0,
        sold: 0,
        slug: 'gau-bong-minions-nieng-rang',
        __v: 0,
    },
    {
        rating: {
            rate: 5,
            count: 0,
        },
        _id: '675c01c744ad6011ea4eced9',
        title: 'Gấu Bông Mihi Doll',
        image: 'https://gaubongonline.vn/wp-content/uploads/2021/05/gau-bong-mihi-7.jpg',
        description: 'Gấu Bông Mihi Doll',
        price: 90000,
        amount: 0,
        seller: 0,
        sold: 0,
        slug: 'gau-bong-mihi-doll',
        __v: 0,
    },
    {
        rating: {
            rate: 5,
            count: 0,
        },
        _id: '675c01f244ad6011ea4ecee0',
        title: 'Chuột Capybara Hồng Rút Nước Mũi',
        image: 'https://gaubongonline.vn/wp-content/uploads/2024/07/Capybara-hong-rut-nuoc-mui-1-500x500.jpg',
        description: 'Chuột Capybara Hồng Rút Nước Mũi',
        price: 157500,
        amount: 0,
        seller: 0,
        sold: 0,
        slug: 'chuot-capybara-hong-rut-nuoc-mui',
        __v: 0,
    },
    {
        rating: {
            rate: 5,
            count: 0,
        },
        _id: '675c021044ad6011ea4ecee4',
        title: 'Gấu Bông Tuần Lộc Baby',
        image: 'https://gaubongonline.vn/wp-content/uploads/2022/09/tuan-loc-baby-1-jpg-500x500.webp',
        description: 'Gấu Bông Tuần Lộc Baby',
        price: 145000,
        amount: 0,
        seller: 0,
        sold: 0,
        slug: 'gau-bong-tuan-loc-baby',
        __v: 0,
    },
    {
        rating: {
            rate: 5,
            count: 0,
        },
        _id: '675c023244ad6011ea4eceeb',
        title: 'Gấu Bông Cây Thông 3 Tầng',
        image: 'https://gaubongonline.vn/wp-content/uploads/2024/11/Cay-Thong-3-Tang-6-500x500.jpg',
        description: 'Gấu Bông Cây Thông 3 Tầng',
        price: 115000,
        amount: 0,
        seller: 0,
        sold: 0,
        slug: 'gau-bong-cay-thong-3-tang',
        __v: 0,
    },
    {
        rating: {
            rate: 5,
            count: 0,
        },
        _id: '675c024d44ad6011ea4eceef',
        title: 'Cánh Cụt Đeo Yếm',
        image: 'https://gaubongonline.vn/wp-content/uploads/2024/05/Canh-cut-deo-yem-1-1-500x500.jpg',
        description: 'Cánh Cụt Đeo Yếm',
        price: 135000,
        amount: 0,
        seller: 0,
        sold: 0,
        slug: 'canh-cut-eo-yem',
        __v: 0,
    },
    {
        rating: {
            rate: 5,
            count: 0,
        },
        _id: '675c027144ad6011ea4ecef3',
        title: 'Gấu Bông Teddy Lông Xoắn Má Hồng',
        image: 'https://gaubongonline.vn/wp-content/uploads/2021/01/gau-bong-teddy-long-xoan-ma-hong-7.jpg',
        description: 'Gấu Bông Teddy Lông Xoắn Má Hồng',
        price: 255000,
        amount: 0,
        seller: 0,
        sold: 0,
        slug: 'gau-bong-teddy-long-xoan-ma-hong',
        __v: 0,
    },
    {
        rating: {
            rate: 5,
            count: 0,
        },
        _id: '675c02b644ad6011ea4ecf0b',
        title: 'Hộp Nhẫn Bông',
        image: 'https://gaubongonline.vn/wp-content/uploads/2023/10/nhan-bong-9-500x500.jpg',
        description: 'Hộp Nhẫn Bông',
        price: 175000,
        amount: 0,
        seller: 0,
        sold: 0,
        slug: 'hop-nhan-bong',
        __v: 0,
    },
];
module.exports = initData;
